spring:
  application:
    name: account-service

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5433/accountdb}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:account-service-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: ${SERVER_PORT:8084}

logging:
  level:
    org.example.accountservice: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.kafka: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

customer:
  service:
    url: ${CUSTOMER_SERVICE_URL:http://localhost:8080}